### ISSUE TITLE
wasp_academy

### ISSUE THREAD

**Issue by Acurich** [Acurich/Wasp_Academy_Homeworks#5]
@GalteXx

**Comment by GalteXx** [comment]
Возможно я чего то упускаю, но я нашел только
Wasp_Academy_Homeworks/wasp_academy/wasp_academy/
И это код Ивана. Кстати .xaml пустой, так что кнопок на MainWindow толком-то не будет.

**Comment by Acurich** [comment]
Чутка не то прикрепил, извиняюсь. Брал код Ивана, чтоб понять то, что требуется, приду домой прикреплю по человечески

**Comment by Acurich** [comment]
@GalteXx

**Comment by GalteXx** [comment]
Дз1 и практику защитал. Жду остальное
