### ISSUE TITLE
finalwpf

### ISSUE THREAD

**Issue by Acurich** [Acurich/Wasp_Academy_Homeworks#9]
@GalteXx

**Comment by GalteXx** [comment]
https://github.com/Acurich/Wasp_Academy_Homeworks/blob/a10c2296d7807d119ed7c7abb4b8626fa53c390d/finalwpf.cs#L25
Отличные названия. Кстати в C# можно называть переменные кириллицей, почему бы не попробовать во время проектной деятельности?
